# Neden Numpy?

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]
b = [2,3,4,5]
a
b

[2, 3, 4, 5]

In [3]:
a

[1, 2, 3, 4]

In [4]:
b

[2, 3, 4, 5]

In [5]:
ab = []

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [6]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [7]:
a*b

array([ 2,  6, 12, 20])

In [8]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [9]:
a = np.array([1,2,3,4,5])

In [10]:
type(a)

numpy.ndarray

In [11]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [12]:
np.array([3.14,4,2,3],dtype="float32")

array([3.14, 4.  , 2.  , 3.  ], dtype=float32)

In [13]:
np.array([3.14,4,2,3],dtype="int")

array([3, 4, 2, 3])

# Sıfırdan array oluşturma

In [14]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((3,5),dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [17]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [18]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
np.random.normal(10,4,(3,4))

array([[ 9.91771397, 12.99454803, 11.30397274,  2.66995097],
       [13.59870484, 14.6488518 ,  9.49691074,  0.68931642],
       [ 3.85105154, 16.3179288 ,  7.01595448,  1.74481338]])

In [20]:
np.random.randint(0,10,(3,3))

array([[5, 2, 5],
       [1, 2, 5],
       [1, 6, 7]])

# Özellikler

* **ndim**: _boyut sayısı_
* **shape**: _boyut bilgisi_
* **size**: _toplam eleman sayısı_
* **dtype**: _array veri tipi_

In [21]:
np.random.randint(10,size = 10)

array([4, 5, 8, 4, 0, 3, 5, 0, 0, 5])

In [22]:
a = np.random.randint(10,size = 10)

In [23]:
a.ndim

1

In [24]:
a.shape

(10,)

In [25]:
a.size

10

In [26]:
a.dtype

dtype('int32')

In [27]:
b = np.random.randint(10,size= (3,5))

In [28]:
b

array([[9, 7, 6, 8, 7],
       [8, 3, 6, 6, 8],
       [3, 6, 1, 1, 4]])

In [29]:
b.ndim

2

In [30]:
b.shape

(3, 5)

In [31]:
b.size

15

In [32]:
b.dtype

dtype('int32')

In [33]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a = np.arange(1,10)

In [36]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a.ndim

1

In [38]:
b = a.reshape((1,9))

In [39]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [40]:
b.ndim

2

# Array Birleştirme (Concatenation)

In [41]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [42]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [43]:
z = np.array([7,8,9])

In [44]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# İki boyut

In [45]:
a = np.array([[1,2,3],
             [4,5,6]])

In [46]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [48]:
x = np.array([1,2,3,99,99,3,2,1])

In [49]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [50]:
a,b,c = np.split(x, [3,5])

In [51]:
a

array([1, 2, 3])

In [52]:
b

array([99, 99])

In [53]:
c

array([3, 2, 1])

# İki Boyutlu Ayırma

In [54]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [56]:
ust , alt = np.vsplit(m,[2])

In [57]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [60]:
sol,sag = np.hsplit(m,[2])

In [61]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [62]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [63]:
v = np.array([2,1,4,3,5])

In [64]:
v

array([2, 1, 4, 3, 5])

In [65]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [66]:
v.sort()

In [67]:
v

array([1, 2, 3, 4, 5])

# İki Boyutlu Array Sıralama

In [68]:
m = np.random.normal(20,5,(3,3))

In [69]:
m

array([[24.62303172, 16.13870188, 18.48277761],
       [12.32619298, 22.52778415, 25.32811871],
       [26.89327988, 20.66270579, 23.15902353]])

In [70]:
np.sort(m,axis=1)

array([[16.13870188, 18.48277761, 24.62303172],
       [12.32619298, 22.52778415, 25.32811871],
       [20.66270579, 23.15902353, 26.89327988]])

In [71]:
np.sort(m,axis=0)

array([[12.32619298, 16.13870188, 18.48277761],
       [24.62303172, 20.66270579, 23.15902353],
       [26.89327988, 22.52778415, 25.32811871]])

# Index ile Elemanlara Erişmek

In [72]:
a = np.random.randint(10,size=10)

In [73]:
a

array([2, 2, 2, 0, 7, 0, 1, 9, 4, 3])

In [74]:
a[0]

2

In [75]:
a[-1]

3

In [76]:
a[0] = 100

In [77]:
a

array([100,   2,   2,   0,   7,   0,   1,   9,   4,   3])

In [78]:
m = np.random.randint(10,size=(3,5))

In [79]:
m

array([[5, 7, 8, 7, 1],
       [8, 6, 1, 5, 3],
       [4, 8, 8, 3, 9]])

In [80]:
m[0,0]

5

In [81]:
m[1,2]

1

In [82]:
m[1,2] = 25

In [83]:
m

array([[ 5,  7,  8,  7,  1],
       [ 8,  6, 25,  5,  3],
       [ 4,  8,  8,  3,  9]])

In [84]:
m[1,4] = 2.2

In [85]:
m

array([[ 5,  7,  8,  7,  1],
       [ 8,  6, 25,  5,  2],
       [ 4,  8,  8,  3,  9]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [86]:
a = np.arange(20,30)

In [87]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [88]:
a[0:3]

array([20, 21, 22])

In [89]:
a[:3]

array([20, 21, 22])

In [90]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [91]:
a[1::2]

array([21, 23, 25, 27, 29])

In [92]:
a[0::2]

array([20, 22, 24, 26, 28])

In [93]:
a[2::2]

array([22, 24, 26, 28])

In [94]:
a[0::3]

array([20, 23, 26, 29])

# İki Boyutlu Slice İşlemleri

In [95]:
m = np.random.randint(10,size = (5,5))
m

array([[0, 6, 9, 0, 0],
       [4, 2, 2, 9, 0],
       [6, 1, 5, 0, 8],
       [5, 9, 6, 8, 5],
       [4, 6, 6, 7, 7]])

In [96]:
m[:,0]

array([0, 4, 6, 5, 4])

In [97]:
m[:,1]

array([6, 2, 1, 9, 6])

In [98]:
m[1,:]

array([4, 2, 2, 9, 0])

In [99]:
m[3,:]

array([5, 9, 6, 8, 5])

In [100]:
m[0:2,0:3]

array([[0, 6, 9],
       [4, 2, 2]])

In [101]:
m[:,0:2]

array([[0, 6],
       [4, 2],
       [6, 1],
       [5, 9],
       [4, 6]])

In [102]:
m[:,:2]

array([[0, 6],
       [4, 2],
       [6, 1],
       [5, 9],
       [4, 6]])

In [103]:
m[::,:2]

array([[0, 6],
       [4, 2],
       [6, 1],
       [5, 9],
       [4, 6]])

In [104]:
m

array([[0, 6, 9, 0, 0],
       [4, 2, 2, 9, 0],
       [6, 1, 5, 0, 8],
       [5, 9, 6, 8, 5],
       [4, 6, 6, 7, 7]])

In [105]:
m[1:3,0:2]

array([[4, 2],
       [6, 1]])

# Alt Küme Üzerinde İşlem Yapmak

In [106]:
a = np.random.randint(10,size=(5,5))
a

array([[2, 9, 6, 5, 8],
       [4, 5, 5, 9, 4],
       [9, 6, 4, 3, 9],
       [2, 4, 1, 8, 4],
       [4, 1, 8, 1, 3]])

In [107]:
alt_a = a[0:3,0:2]
alt_a

array([[2, 9],
       [4, 5],
       [9, 6]])

In [108]:
alt_a[0,0] = 999
alt_a[1,1] = 888

In [109]:
alt_a

array([[999,   9],
       [  4, 888],
       [  9,   6]])

In [110]:
a

array([[999,   9,   6,   5,   8],
       [  4, 888,   5,   9,   4],
       [  9,   6,   4,   3,   9],
       [  2,   4,   1,   8,   4],
       [  4,   1,   8,   1,   3]])

# Kopya Yöntemi ile Orjinal Matrisi Koruma

In [111]:
m = np.random.randint(10,size=(5,5))
m

array([[3, 3, 8, 7, 6],
       [2, 2, 8, 0, 0],
       [9, 0, 3, 6, 1],
       [3, 6, 8, 1, 7],
       [8, 0, 7, 6, 8]])

In [112]:
alt_m = m[0:3,0:2].copy()
alt_m

array([[3, 3],
       [2, 2],
       [9, 0]])

In [113]:
alt_m[0,0] = 999
alt_m[1,1] = 888

In [114]:
alt_m

array([[999,   3],
       [  2, 888],
       [  9,   0]])

In [115]:
m

array([[3, 3, 8, 7, 6],
       [2, 2, 8, 0, 0],
       [9, 0, 3, 6, 1],
       [3, 6, 8, 1, 7],
       [8, 0, 7, 6, 8]])

# Fancy Index ile Elemanlara Erişmek (Önemli)

In [116]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [117]:
v[1]

3

In [118]:
v[3]

9

In [119]:
v[5]

15

In [120]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [121]:
al_getir = [1,3,5]

In [122]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [123]:
v[al_getir]

array([ 3,  9, 15])

# İki Boyutta Fancy

In [124]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [125]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [126]:
m[satir,sutun]

array([1, 5])

# Basit Index ile Fancy Index

In [127]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [128]:
m[0,[1,2]]

array([1, 2])

# Slice ile Fancy

In [129]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [130]:
v = np.array([1,2,3,4,5])

In [131]:
v < 3

array([ True,  True, False, False, False])

In [132]:
v[v<3]

array([1, 2])

In [133]:
v[v>3]

array([4, 5])

In [134]:
v[v>=3]

array([3, 4, 5])

In [135]:
v[v<=3]

array([1, 2, 3])

In [136]:
v[v==3]

array([3])

In [137]:
v[v!=3]

array([1, 2, 4, 5])

In [138]:
v

array([1, 2, 3, 4, 5])

In [139]:
v * 2

array([ 2,  4,  6,  8, 10])

In [140]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [141]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [142]:
v**2

array([ 1,  4,  9, 16, 25])

# Matematiksel İşlemler

In [143]:
v = np.array([1,2,3,4,5])

In [144]:
v - 1

array([0, 1, 2, 3, 4])

In [145]:
v * 5

array([ 5, 10, 15, 20, 25])

In [146]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [147]:
v * 5 / 10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

# ufunc

In [148]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [149]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [150]:
np.multiply(v,1)

array([1, 2, 3, 4, 5])

In [151]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [152]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [153]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [154]:
np.sqrt(v)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [155]:
np.absolute(np.array([-3]))

array([3])

In [156]:
np.sin(360)

0.9589157234143065

In [157]:
np.cos(180)

-0.5984600690578581

In [158]:
v = np.array([1,2,3])

In [159]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [160]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [161]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\tolga\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\tolga\appdata\local\programs\python\python310\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippe

In [162]:
# python numpy cheat sheet

In [163]:
# numpy statistics cheat sheet

# NumPy ile İki Bilinmeyenli Denklem Çözümü

* 5x + y = 12
* x + 3y = 10

In [164]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [165]:
a

array([[5, 1],
       [1, 3]])

In [166]:
b

array([12, 10])

In [167]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])